#!/bin/bash -
#-----------------------------------------------------------------------
#  Shell script to create Ubuntu desktop configuration files.
#  These files are of the type, application/x-desktop.
#-----------------------------------------------------------------------
#  cconf is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as 
#  published by the Free Software Foundation, either version 3 of the 
#  License, or any later version.
#
#  cconf is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.                          
#                                                                        
#  You should have received a copy of the GNU General Public License
#  along with cconf. If not, see http://www.gnu.org/licenses
#-----------------------------------------------------------------------
#  Author: Rohan Pinto
#  Email: rohan62442@hotmail.com
#-----------------------------------------------------------------------

if [[ $1 == *.desktop ]]
then
	fname=$1
else
	fname=$1.desktop
fi
touch $fname
echo "[Desktop Entry]" > $fname

function entries() {
	echo -n "$1="
	read x
	if [ -n "$x" ] 
	then
		echo "$1=$x" >> $fname
	fi
}

entries Name
entries Version
entries Exec
entries Icon
entries Terminal
entries Type
entries Categories
entries MimeType
entries Action
entries StartupNotify

entries Comment
entries Keywords
entries GenericName

entries OnlyShowIn
entries NotShowIn

entries X-GNOME-Bugzilla-Bugzilla
entries X-GNOME-Bugzilla-Product
entries X-GNOME-Bugzilla-Component
entries X-GNOME-Bugzilla-Version
entries X-GNOME-UsesNotifications
entries X-GNOME-Settings-Panel
entries X-GNOME-FullName
entries X-GNOME-Gettext-Domain

entries X-Unity-IconBackgroundColor
entries X-Ayatana-Appmenu-Show-Stubs
entries X-GIO-NoFuse

entries X-Ubuntu-Gettext-Domain

echo >> $fname
echo
echo "<--Config File Begins Here-->"
cat $fname
echo "<---Config File Ends Here--->"
