#!/bin/bash -
#-----------------------------------------------------------------------
#  Bash script to install essential packages in Ubuntu desktop.
#  In addition to this, it also removes unnecessary packages. This
#  script requires root level privileges.
#-----------------------------------------------------------------------
#  install-essential is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as 
#  published by the Free Software Foundation, either version 3 of the 
#  License, or any later version.
#
#  install-essential is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.                          
#                                                                        
#  You should have received a copy of the GNU General Public License
#  along with install-essential. If not, see http://www.gnu.org/licenses
#-----------------------------------------------------------------------
#  Author: Rohan Pinto
#  Email: rohan62442@hotmail.com
#-----------------------------------------------------------------------

if [[ $EUID -ne 0 ]]; then
	echo "install-essential: This script must be run as root."
	exit 1
fi

function installer() {
	for pack
	do
		apt-get install $pack
	done
}

function remover() {
	for pack
	do
		apt-get remove --purge $pack
	done
}

apt-get update
apt-get upgrade

#INSTALLATIONS

#Miscellaneous
installer ubuntu-restricted-extras ubuntu-restricted-addons
installer unity-tweak-tool gimp synaptic checkinstall
installer fbreader gnome-mplayer mesa-utils dkms
installer gweled transmageddon cx-freeze

#Printing and Scanning
installer avahi-utils libcups2 cups libcups2-dev cups-bsd cups-client 
installer libcupsimage2-dev libdbus-1-dev build-essential ghostscript
installer openssl libjpeg-dev libsnmp-dev libtool libusb-1.0.0-dev xsane
installer python-imaging policykit-1 policykit-1-gnome gtk2-engines-pixbuf
installer python-qt4 python-qt4-dbus python-dbus python-gobject python-dev
installer python-notify python python-reportlab libsane libsane-dev sane-utils 

#Multimedia Codecs and DVD playback
installer gstreamer0.10-plugins-ugly gstreamer0.10-ffmpeg
installer mencoder libdvdread4 icedax gstreamer0.10-plugins-bad-multiverse
installer libmad0 gstreamer0.10-plugins-bad
if [ -e /usr/share/doc/libdvdread4/install-css.sh ] && [ -x /usr/share/doc/libdvdread4/install-css.sh ]
then
	/usr/share/doc/libdvdread4/install-css.sh
fi
installer libavformat-extra-53 libavcodec-extra-53

installer openjdk-7-jdk openjdk-7-jre icedtea-7-jre-jamvm java-common			#Java
installer p7zip-full unrar p7zip p7zip-rar cabextract zip unzip					#Archiving
installer flashplugin-installer													#Flash
installer compizconfig-settings-manager											#ccsm
installer gufw lynis rkhunter chkrootkit gnupg gnupg-agent						#Security
installer git git-man subversion mercurial										#VCS
installer libc6:i386 libstdc++6:i386 zlib1g:i386								#x86 libs for ADT

#REMOVALS

remover totem totem-plugins totem-mozilla										#Totem player
remover unity-scope-gdrive														#Unity scopes
