#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root."
	exit 1
fi
if [ ! -f $1 ]; then
    echo "File $1 not found!"
else
	cp $1 /usr/share/backgrounds
	mv /usr/share/backgrounds/$1 /usr/share/backgrounds/warty-final-ubuntu.png
fi